services:
  nuxt:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: 'invoice-management-system'
      MYSQL_USER: 'localhost'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nestjs:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    image: nestjs_dev
    container_name: nestjs_dev
    command: npm run start:prod
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: ''
      DATABASE_NAME: invoice-management-system
